Adds Encryption utils for AES
dimagi/commcare-core pull request #1003
Opened 2021-06-17 11:22 UTC by shubham1g5

Refactors AES encryption methods inside a utility class.

2021-06-25 14:49 UTC, ctsims requested changes
These kinds of methods are really important to document clearly, since the details of how something is encrypted matter quite a bit. Since this is now something that is going to be a more "library" kind of method I think it's a really good opportunity to document a bit more clearly.

I made some initial suggestions on what should be more clear, but it might make more sense to document the class javadoc instead outlining the details, and then leaving the method specific details less verbose. 

One big remaining point of documentation, though: When working with these kinds of encryption methods which are intended to consume inputs that come from another system or provide outputs which could be read by another system (a base64 encoded payload with the IV and ciphertext), it's really, really helpful to be more specific than you might think you need to be about those elements.

The user story I'm thinking of is someone who needs to generate the symmetric key that will be used here. Someone will need to create that key, and it will probably be the case that they won't be using this Java library to do so, so they'll need to know exactly what to do in a totally separate system. There are [multiple base64](https://en.wikipedia.org/wiki/Base64#Implementations_and_history) encoding schemes, for instance, and which one is the "Default" is very different between platforms.

I'd recommend both being specific about any of the relevant details, but also potentially including a code snippet (in the commcare-core wiki docs, probably) in python which will generate a compatible key.

2021-06-25 14:49 UTC, ctsims commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * Encrypts a message using the AES encryption
```suggestion
     * Encrypts a message using the AES encryption and produces a base64 encoded payload containing the ciphertext, and a random IV which was used to encrypt the input.
```

2021-06-25 14:49 UTC, ctsims commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * @param message a message to be encrypted
```suggestion
     * @param message a UTF-8 encoded message to be encrypted 
```

2021-06-25 14:49 UTC, ctsims commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * @param key     the key used for encryption
```suggestion
     * @param key     A base64 encoded 256 bit symmetric key
```

2021-06-25 14:49 UTC, ctsims commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * @return AES encrypted message using the given key
A base64 encoded payload containing the IV and AES encrypted ciphertext, which can be decoded by this utility's decrypt method and the same symmetric key

2021-06-25 14:49 UTC, ctsims commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * Decrypts a message encoded with the AES encryption
```suggestion
     * Decrypts a base64 payload containing an IV and AES encrypted ciphertext using the provided key
```

2021-06-25 14:50 UTC, ctsims commented
@shubham1g5 Let me know if this is time sensitive, btw. I do think we should make the changes I mentioned, but I don't want to block work on them if we need to get this in for the release

2021-06-28 12:58 UTC, shubham1g5 commented on src/main/java/org/commcare/util/EncryptionUtils.java
> +     * @return AES encrypted message using the given key
```suggestion
     * @return A base64 encoded payload containing the IV and AES encrypted ciphertext, which can be decoded by this utility's decrypt method and the same symmetric key
```

2021-06-29 17:59 UTC, ctsims approved these changes
Approving for now based on our conversation, we can plan out key docs after initital testing

2021-07-14 18:42 UTC, merged