Rc/instance refs menus without children
dimagi/commcare-core pull request #1294
Opened 2023-06-06 17:48 UTC by Robert-Costello

## Technical Summary

This is a first pass at supporting instance references in menus without children. Planning to get some notes on these changes an possibly transfer then over to https://github.com/dimagi/commcare-core/pull/1266
## Safety Assurance

### Safety story

### Automated test coverage

### QA Plan

### Special deploy instructions

- [ ] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations.

### Review

- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

2023-06-07 17:37 UTC, shubham1g5 requested changes

2023-06-07 17:37 UTC, shubham1g5 commented on src/main/java/org/commcare/suite/model/GetLimitedInstances.java
> +public class GetLimitedInstances {
Actially we can just put the method in this class into `InstanceUtils` instead of creating a new class.

2023-06-07 17:37 UTC, shubham1g5 commented on src/main/java/org/commcare/xml/EntryParser.java
> +//    private void parseInstance(Hashtable<String, DataInstance> instances) {
can remove

2023-06-07 17:37 UTC, shubham1g5 commented on src/main/java/org/commcare/xml/MenuParser.java
> +            } else if (tagName.toLowerCase().equals("instance")) {
we should add corresponding tests for menu -> instances parsing

2023-06-09 18:57 UTC, Robert-Costello commented on src/main/java/org/commcare/session/CommCareSession.java
> +            Hashtable<String, DataInstance> instancesInScope) {
I don't remember why this was there. Doesn't need to be. fix here [93f764b](https://github.com/dimagi/commcare-core/pull/1294/commits/93f764b157193f0e1ed502ff8f9d05c6c1727d49)

2023-07-14 19:28 UTC, closed without merging