Add flag if to show borders on case list fields
dimagi/commcare-core pull request #1381
Opened 2023-11-21 15:34 UTC by MartinRiese

## Product Description

Add flag to case list fields to show a border

## Technical Summary

https://dimagi-dev.atlassian.net/browse/USH-3823

## Safety Assurance

### Safety story

Only additive

### Automated test coverage

### QA Plan

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

2023-11-21 15:43 UTC, shubham1g5 requested changes

2023-11-21 15:43 UTC, shubham1g5 commented on src/main/java/org/commcare/suite/model/DetailField.java
> +    private boolean showBorder;
Feels like this should be part of [Style](https://github.com/dimagi/commcare-core/blob/master/src/main/java/org/commcare/suite/model/Style.java) instead

2023-11-27 17:27 UTC, shubham1g5 commented
Can we update the [doc](https://github.com/dimagi/commcare-core/wiki/Suite20) with the attribute as well ? Thanks!

2023-11-27 17:40 UTC, MartinRiese commented
Updated the doc

2023-11-27 17:41 UTC, MartinRiese commented
duplicate this PR

2023-11-28 02:37 UTC, merged