Add flag to show different shading on case tile fields
dimagi/commcare-core pull request #1393
Opened 2023-12-20 20:20 UTC by Robert-Costello

## Product Description

Add flag to show different shading on case tile fields
## Technical Summary

jira ticket: https://dimagi-dev.atlassian.net/browse/USH-3952
## Safety Assurance

### Safety story

### Automated test coverage

### QA Plan

### Special deploy instructions

- [x] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations.

### Review

- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

2023-12-20 20:23 UTC, shubham1g5 requested changes
Can we also add a test similar to [this PR](https://github.com/dimagi/commcare-core/pull/1381/files#diff-f3bc7e676d27c78b8b327bb6dbe1406d26a55f27d2ca0a6b44c0e79e1d9eb3bf)

2023-12-20 20:36 UTC, shubham1g5 approved these changes

2023-12-20 20:37 UTC, Robert-Costello commented
duplicate this PR

2023-12-21 03:30 UTC, MartinRiese approved these changes

2023-12-21 19:29 UTC, merged