Fix Levenshtein distance algorithm
dimagi/commcare-core pull request #1431
Opened 2024-09-03 13:24 UTC by avazirna

## Product Description
This PR fixes a small issue with the Levenshtein distance calculation, which was causing the fuzzy search to return false positives. For instance, the difference between `aply` into `cape` was previously 2 while it should be 3, and because our distance threshold is set at 2, the cape was a valid value for `aply`.

Another look to the [source of the algorithm](https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance), I could also confirm that this was initially incorrect and later on updated to the current form:
```
		// initial cost of skipping prefix in String s1
		newcost[0]=j;
```
Ticket: https://dimagi.atlassian.net/browse/SAAS-15738

## Technical Summary

## Safety Assurance

### Automated test coverage
There are unit tests around this feature and they seem to have not been affected by this change.

### Special deploy instructions

- [X] This PR can be deployed after merge with no further considerations.

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations.

### Review

- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change.

### Duplicate PR
Automatically duplicate this PR as defined in [contributing.md](https://github.com/dimagi/commcare-core/blob/master/.github/contributing.md).

2024-09-03 14:01 UTC, shubham1g5 requested changes
Looks good to me though can we write a unit test for the particular edge case we are trying to fix here.

2024-09-04 02:08 UTC, shubham1g5 approved these changes

2024-09-04 08:05 UTC, avazirna commented
Duplicate PR

2024-09-04 08:06 UTC, avazirna commented
duplicate this PR

2024-09-04 08:06 UTC, merged